name: CI workflow

on: [push, pull_request]
  
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - name: Build tool
      run: go build -v ./...
